on:
  workflow_dispatch:

jobs:
  test_job:
    name: Node Information
    runs-on: sslab-kuase
    steps:
      - name: check the node version
        run: cat /etc/issue && uname -a
      - name: check the node spec
        run: lscpu ; lsmem
